apiVersion: v1
kind: Pod
metadata:
  name: scenario-20-missing-secret
  labels:
    scenario: "20"
    category: config
spec:
  containers:
  - name: crasher
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: app-secret-does-not-exist
          key: API_KEY
