apiVersion: v1
kind: Secret
metadata:
  name: scenario-48-bad-regcred
  labels:
    scenario: "48"
    category: network
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoid3JvbmctdXNlciIsInBhc3N3b3JkIjoid3JvbmctcGFzcyIsImF1dGgiOiJkM0p2Ymkxd1lYTnpkMjl5WkRwd1lYTnpkMjl5Wmk0PSJ9fX0=
---
apiVersion: v1
kind: Pod
metadata:
  name: scenario-48-bad-pullsecret
  labels:
    scenario: "48"
    category: network
spec:
  imagePullSecrets:
  - name: scenario-48-bad-regcred
  containers:
  - name: crasher
    image: ghcr.io/some-private-org/some-image:latest
