apiVersion: v1
kind: Pod
metadata:
  name: scenario-41-rate-limit
  labels:
    scenario: "41"
    category: network
spec:
  containers:
  - name: crasher
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["echo 'ERROR: toomanyrequests: You have reached your pull rate limit'; exit 1"]
