apiVersion: v1
kind: Pod
metadata:
  name: scenario-33-bad-repo
  labels:
    scenario: "33"
    category: config
spec:
  containers:
  - name: crasher
    image: thisdoesnotexist.invalid/nonexistent-image:latest
