apiVersion: v1
kind: Pod
metadata:
  name: scenario-06-liveness
  labels:
    scenario: "06"
    category: resource
spec:
  containers:
  - name: crasher
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    livenessProbe:
      exec:
        command: ["/bin/sh", "-c", "exit 1"]
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 2
